FROM python:3.12.10-slim

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=0 \
    PIP_CACHE_DIR=/root/.cache/pip \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_CACHE_DIR=/root/.cache/pypoetry

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && apt-get clean

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -

# Add Poetry to PATH
ENV PATH="/root/.local/bin:$PATH"

# Install the poetry-plugin-export plugin
RUN poetry self add poetry-plugin-export

COPY pyproject.toml poetry.lock ./

RUN --mount=type=cache,target=/root/.cache/pip poetry install --no-root --only main

RUN poetry add --group dev debugpy watchgod
COPY . .

EXPOSE 8000

CMD ["python", "-m", "app"]
