services:
  debug-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rag-debug-test
    command:
      [
        "poetry", "run", "python", "-Xfrozen_modules=off", "-m", "debugpy",
        "--listen", "0.0.0.0:5678", "--wait-for-client", "-m", "pytest", "tests"
      ]
    ports:
      - "5680:5678"
    volumes:
      - .:/app
      - ./documents:/app/documents
      - ./chroma:/app/chroma
      - poetry_deps:/opt/poetry_deps
    environment:
      - PYTHONUNBUFFERED=1
      - PYTEST_PDF=/app/tests/images_document.pdf
