volumes:
  poetry_deps:

services:
  backend:
    container_name: rag-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["python", "-m", "app.dev", "entrypoints/run_backend.py"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./documents:/app/documents
      - ./chroma:/app/chroma
      - poetry_deps:/opt/poetry_deps
    environment:
      - PYTHONUNBUFFERED=1

  cli:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rag-cli
    command: ["python", "-m", "app.dev", "entrypoints/run_cli.py"]
    volumes:
      - .:/app
      - ./documents:/app/documents
      - ./chroma:/app/chroma
      - poetry_deps:/opt/poetry_deps
    ports:
      - "5678:5678"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - backend

  test:
    container_name: rag-test
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - poetry_deps:/opt/poetry_deps
    environment:
      - PYTHONUNBUFFERED=1
      - PYTEST_PDF=/app/tests/images_document.pdf
    command: ["poetry", "run", "pytest", "tests"]
    restart: "no"
