volumes:
  poetry_deps:

services:
  backend:
    container_name: rag-backend-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: ["python", "-m", "app.dev", "entrypoints/run_backend.py"]
    ports:
      - "8000:8000"
      - "5679:5678"
    volumes:
      - .:/app
      - ./documents:/app/documents
      - ./chroma:/app/chroma
      - poetry_deps:/opt/poetry_deps
    environment:
      - PYTHONUNBUFFERED=1

  cli:
    container_name: rag-cli-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: ["python", "-m", "app.dev", "entrypoints/run_cli.py"]
    volumes:
      - .:/app
      - ./documents:/app/documents
      - ./chroma:/app/chroma
      - poetry_deps:/opt/poetry_deps
    ports:
      - "5678:5678"
    depends_on:
      - backend

  test:
    container_name: rag-test
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: ["poetry", "run", "pytest", "tests"]
    volumes:
      - .:/app
      - poetry_deps:/opt/poetry_deps
    environment:
      - PYTHONUNBUFFERED=1
      - PYTEST_PDF=/app/tests/images_document.pdf
    restart: "no"

  debug-test:
    extends:
      service: test
    ports:
      - "5680:5678"
    command: ["poetry", "run", "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "-m", "pytest", "tests"]
