volumes:
  poetry_deps:

services:
  debug-test:
    container_name: local-rag-debug-test
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
      - poetry_deps:/opt/poetry_deps
    environment:
      - PYTHONUNBUFFERED=1
      - PYTEST_PDF=/app/tests/images_document.pdf
    ports:
      - "5680:5678"
    command:
      [
        "poetry",
        "run",
        "python",
        "-Xfrozen_modules=off",
        "-m",
        "debugpy",
        "--listen",
        "0.0.0.0:5678",
        "--wait-for-client",
        "-m",
        "pytest",
        "tests",
      ]
    restart: "no"

  test:
    container_name: local-rag-test
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
      - poetry_deps:/opt/poetry_deps
    environment:
      - PYTHONUNBUFFERED=1
      - PYTEST_PDF=/app/tests/images_document.pdf
    command: ["poetry", "run", "pytest", "tests"]
    restart: "no"

  backend:
    container_name: rag-backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["python", "-m", "app.dev", "entrypoints/run_backend.py"]
    ports:
      - "8000:8000"
      - "5679:5678"
    volumes:
      - .:/app
      - ./documents:/app/documents
      - ./chroma:/app/chroma
      - poetry_deps:/opt/poetry_deps
    environment:
      - PYTHONUNBUFFERED=1

  cli:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rag-cli-dev
    command: ["python", "-m", "app.dev", "entrypoints/run_cli.py"]
    volumes:
      - .:/app
      - ./documents:/app/documents
      - ./chroma:/app/chroma
      - poetry_deps:/opt/poetry_deps
    ports:
      - "5678:5678"
    depends_on:
      - backend
